export function exportAsMarkdown(title: string, content: string): void {
  const blob = new Blob([`# ${title}\n\n${content}`], { type: 'text/markdown' });
  downloadBlob(blob, `${slugify(title)}.md`);
}

export function exportAsPrintHTML(title: string, bodyHtml: string): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: 'IBM Plex Sans', system-ui, sans-serif; font-size: 10pt; color: #000; max-width: 800px; margin: 0 auto; padding: 20px; }
  h1 { font-family: 'IBM Plex Sans', system-ui, sans-serif; font-size: 18pt; font-weight: 600; border-bottom: 2px solid #d4a843; padding-bottom: 8px; }
  h2 { font-family: 'IBM Plex Sans', system-ui, sans-serif; font-size: 14pt; font-weight: 600; margin-top: 20px; color: #333; }
  h3 { font-size: 11pt; margin-top: 16px; color: #555; }
  .control-id { font-family: 'IBM Plex Mono', monospace; font-weight: 600; color: #d4a843; }
  .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 8pt; font-weight: 600; margin-left: 4px; }
  .badge-new { background: #fef3c7; color: #92400e; }
  ul { margin: 4px 0; padding-left: 20px; }
  li { margin: 2px 0; }
  .checkbox { margin-right: 6px; }
  .notes { border: 1px solid #ccc; border-radius: 4px; padding: 8px; min-height: 40px; margin: 8px 0; background: #fafafa; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; font-size: 9pt; }
  th { background: #f3f4f6; font-weight: 600; }
  .status-compliant { color: #059669; }
  .status-partial { color: #d97706; }
  .status-non-compliant { color: #dc2626; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
<h1>${title}</h1>
${bodyHtml}
<footer style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 8pt; color: #999;">
Generated by Post_Watch — ISO 27001:2022 Toolkit
</footer>
</body>
</html>`;
  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, `${slugify(title)}.html`);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
